name: nodejs-ecal-CI
on: [pull_request]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm ci
        run: |
          npm ci
      - run: npm test
        run: |
          npm test
