name: nodejs-ecal-CI
on: [pull_request]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest] # not sure how we would install ecal on windows
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies (Ecal, CMake, g++, protobuf)
        run: |
          sudo add-apt-repository ppa:ecal/ecal-latest
          sudo apt-get update
          sudo apt-get install ecal cmake g++ libprotobuf-dev protobuf-compiler

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm ci
        run: |
          npm ci
      - name: npm test
        run: |
          npm test
